#!/usr/bin/env python3

from http.server import HTTPServer, SimpleHTTPRequestHandler
import appKmeans as km
import cgi

PORT = 8080


class MyHTTPRequestHandler(SimpleHTTPRequestHandler):
    def do_POST(self):
        print("heeeeyy")
        form = cgi.FieldStorage(
            fp=self.rfile,
            headers=self.headers,
            environ={'REQUEST_METHOD':'POST',
            'CONTENT_TYPE':self.headers['Content-Type'],
            })
        image = form.getvalue("image")
        print(image)
        self.send_response(200)
        self.send_header("Content-type", "text/html")
        self.end_headers()
        km.run(image, 3)

        with open('response.html', 'rb') as file:
            data = file.read()

        self.wfile.write(data)

def main():
    httpd = HTTPServer(('', PORT), MyHTTPRequestHandler)
    print('Serving at port ' + str(PORT))
    httpd.serve_forever();

if __name__ == '__main__':
    main()
